-- ═══════════════════════════════════════════════════════════════════════
--  T-0 Fitness Platform Database Initialization Schema
--  Paste this entire query block into the Supabase SQL Editor to initialize.
-- ═══════════════════════════════════════════════════════════════════════

-- 1. Create Profiles Table (for Coaches and Trainees)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  role TEXT CHECK (role IN ('coach', 'trainee')),
  specialty TEXT,
  bio TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Coach-Client Relationships
CREATE TABLE IF NOT EXISTS public.coach_clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  trainee_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  goal TEXT,
  weight TEXT,
  weekly_sessions TEXT,
  notes TEXT,
  progress INTEGER DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  tag TEXT DEFAULT 'new' CHECK (tag IN ('new', 'active', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(coach_id, trainee_id)
);

-- 3. Create Workout Plans Table
CREATE TABLE IF NOT EXISTS public.workout_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  trainee_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  day_label TEXT,
  items JSONB, -- Stores the list of exercises
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Diet Plans Table
CREATE TABLE IF NOT EXISTS public.diet_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  trainee_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  day_label TEXT,
  items JSONB, -- Stores the list of meals
  sort_order INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coach_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diet_plans ENABLE ROW LEVEL SECURITY;

-- 6. Re-create Security Policies
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Coaches manage their clients" ON public.coach_clients;
CREATE POLICY "Coaches manage their clients" ON public.coach_clients FOR ALL USING (auth.uid() = coach_id);

DROP POLICY IF EXISTS "Trainees view their coach" ON public.coach_clients;
CREATE POLICY "Trainees view their coach" ON public.coach_clients FOR SELECT USING (auth.uid() = trainee_id);

DROP POLICY IF EXISTS "Coaches manage workout plans" ON public.workout_plans;
CREATE POLICY "Coaches manage workout plans" ON public.workout_plans FOR ALL USING (auth.uid() = coach_id);

DROP POLICY IF EXISTS "Coaches manage diet plans" ON public.diet_plans;
CREATE POLICY "Coaches manage diet plans" ON public.diet_plans FOR ALL USING (auth.uid() = coach_id);

DROP POLICY IF EXISTS "Trainees view workout plans" ON public.workout_plans;
CREATE POLICY "Trainees view workout plans" ON public.workout_plans FOR SELECT USING (auth.uid() = trainee_id);

DROP POLICY IF EXISTS "Trainees view diet plans" ON public.diet_plans;
CREATE POLICY "Trainees view diet plans" ON public.diet_plans FOR SELECT USING (auth.uid() = trainee_id);

-- 7. Trigger to automatically create a profile record when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'role', 'trainee')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
-- ═══════════════════════════════════════════════════════════════════════
--  T-0 Schema Update: Trainee Self-Plans
--  Run this block after the initial schema to enable trainee-owned plans.
-- ═══════════════════════════════════════════════════════════════════════

-- Add created_by column to distinguish coach-assigned vs trainee-owned plans
ALTER TABLE public.workout_plans ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT 'coach' CHECK (created_by IN ('coach', 'trainee'));
ALTER TABLE public.diet_plans ADD COLUMN IF NOT EXISTS created_by TEXT DEFAULT 'coach' CHECK (created_by IN ('coach', 'trainee'));

-- Allow trainees to fully manage their own plans
DROP POLICY IF EXISTS "Trainees manage own workout plans" ON public.workout_plans;
CREATE POLICY "Trainees manage own workout plans" ON public.workout_plans FOR ALL
  USING (auth.uid() = trainee_id AND created_by = 'trainee')
  WITH CHECK (auth.uid() = trainee_id AND created_by = 'trainee');

DROP POLICY IF EXISTS "Trainees manage own diet plans" ON public.diet_plans;
CREATE POLICY "Trainees manage own diet plans" ON public.diet_plans FOR ALL
  USING (auth.uid() = trainee_id AND created_by = 'trainee')
  WITH CHECK (auth.uid() = trainee_id AND created_by = 'trainee');
